### ISSUE TITLE
isSuggestionsVisible() method not available in Version: 0.7.1

### ISSUE THREAD

**Issue by EdwardQuixote** [mancj/MaterialSearchBar#50]
I can't check if my search suggestions list is visible or not.
I dug a bit deeper and found out in version `0.7.1`, the public method `MaterialSearchBar.isSuggestionsVisible()` isn't available.

**Comment by GitUser4732** [comment]
There hasn't been a new release since that method was added.
Until mancj creates new release, you could use my temporary release which contains the Style Support  Pull request changes/additions in which `isSuggestionsVisible()` was added.
`compile 'com.github.GitUser4732:MaterialSearchBar:v0.8-beta'`
